version: "3.3"

# networks:
#   monitor-net:
#     driver: host

services:
  freepbx:
    image: leopguimaraes/freepbx:testing
    # expose:
    #   - 80
    #   - 5060/udp
    ports:
      - 80:80
      - 443:443
      #- 3306:3306
      - 5060:5060/udp
    #network_mode: bridge
    networks:
      rede-docker: 
    volumes:
      - asterisk-data:/etc/asterisk
      - ${CONFIG}/freepbxcontainer/freepbx.conf:/etc/freepbx.conf:Z
    privileged: true

  mysql:
    image: leopguimaraes/freepbx:banco
    ports:
      - 3306:3306
    networks:
      rede-docker:
    volumes:
      - mysql-data:/var/lib/mysql
    privileged: true

volumes:
  asterisk-data:
  mysql-data:
networks:
  rede-docker: